### ISSUE TITLE
Luro operational improvements

### ISSUE THREAD

**Issue by bf-monster** [betfinio/games#41]
Those are testing outputs, coming out of my observation @bf-tom please check and create new tasks as this is just list and may be not conceptional.. discuss with @bf-monster. PI will be testing the website like this time to time, it is needed to sort the points as bugs, duplicities and feature tasks.

- [x] Bonus questionmark is displayednot as "?" but as "!"
- [x] Modal in bonus questionmark doesn't display any content
- [x] When I click spin the wheel after the round ends, it opens metamask, but there is no action afterwards - the button "spin the wheel" remains there and I next click creates an error. If you jum to round detail in the round history, there is round spinning but that has to happen also in the main window after button click!
- [x] If I am in the ended round after it is spinned and I click "back to game" button, the new round window opens incorrectly. The LURO chart is blured and the button "back to game" is still there and does not work anymore. There has to be complete refresh.
- [x] The dragging bar 0%-100% has really small space where it reacts to user. Please make it more soft and friendly to use. 
- [ ] Please let me know about the LURO automation. The proposed concept is to execute the SPIN just when the round ends. The previous points of 3 and 4 has to be completely done. 
- [x] Add some effects for the round spinning
- [x] Once the round is ended and no more bets are accepted there can be some effect that is gonna fill the time between the END ROUND and START SPIN ( before the spinning starts}. Make the round steady and put there some animation that makes people to expect something happens. 
- [x] Last 20 seconds of ending time should make some PULSE effect in the time countdown to emphasize the the hurry effect.
- [x] Spinning can be from SLOW to FAST. Now it goes like it starts from the middle...
- [x] Instead of boring text "ended" in the middle of LURO chart there can be a logo of CHAINLINK changing its colours or making some effects while random number is generated. 
- [x] Chosen colour can make some effect on the screen if I don't win
- [x] Add some effects when new bets are placed also to the tables to make it more juicy.
- [x] Existing users can make effects of moving higher in the table
- [ ] Existing user can shine by its color
- [x] New user can make some "popping" effect when appearing in the table

**Comment by bf-tom** [comment]
new requests from J:
- [ ] Make those 3 border next to each other on the top
- [ ] Number of bets in round detail to be away from phone. 
- [ ] Merge result and total result. There should be total result only. The winner is first and green, the rest is white. 
- [ ] Make the user address to look better - to be on 1 row instead of the deleted space
- [ ] Results per page - pls update the font size or somehow fit on one row. This looks like error
- [ ] The winner in round detail should not display the % propbability of winning but just bet amount and win amount. 
     - Put bet amount instead of share/peobability
     - instead of current bet amount there should be win amount, centered above the 7.33x win.
- [ ] Additional: it would be super cool to have the luro with betting space on one page withiut need of scrlling. Let’s make this together
     - i would make narrower upper bar with luro and number. 
     - remove “place bet” headline in phone
     - consider to put away the border with luroto save space 
     - instead of “expected winning of this bet” we can write just WIN 9,714 + bonus and save some space again
